/* Arabic copy for the reel (index.html?lang=ar).
   Keys are the exact English strings rendered by reel.js. Interface copy uses
   the site's light Modern Standard Arabic; customer messages are Gulf dialect. */
window.AR = {
  /* captions + end card + dynamic labels */
  'AI · Live': 'AI · مباشر',
  'Analyzing…': 'جارٍ التحليل…',
  'AI · Insights': 'تنبيهات ذكية',
  '4 insights': '4 تنبيهات',
  'BUSINESS OPERATING PLATFORM': 'منصة تشغيل أعمال',
  'Discover Velorci': 'اكتشف velorci',

  /* chats (customers write in Gulf dialect) */
  'WhatsApp Business': 'واتساب للأعمال',
  'Customer chats': 'محادثات العملاء',
  'Hi, is my order ready?': 'هلا، طلبي جاهز؟',
  'Do you deliver today?': 'توصلون اليوم؟',
  'Checking now…': 'لحظة أتأكد…',
  'Hello??': 'ألو؟؟',
  'Hello?': 'ألو؟',
  'Price please': 'بكم لو سمحت؟',
  'Still waiting…': 'للحين أنتظر…',
  'Can I pay cash?': 'أقدر أدفع كاش؟',
  'Instagram Direct': 'رسائل إنستغرام',
  '9 conversations': '9 محادثات',
  'I want to order 2 pieces': 'أبي أطلب قطعتين',
  'Still available in grey?': 'موجود رمادي؟',
  'Let me check': 'خلني أشوف',
  'Do you ship to Salmiya?': 'توصلون السالمية؟',
  'Delivery group': 'قروب التوصيل',
  'Driver is late again': 'السايق متأخر مرة ثانية',
  'Address unclear': 'العنوان مو واضح',
  'Calling now': 'أتصل الحين',
  'New chat': 'محادثة جديدة',
  'Anyone there?': 'أحد موجود؟',
  '214 chats waiting': '214 محادثة بانتظار الرد',
  '214 waiting': '214 بانتظار الرد',
  'Where is my order?': 'وين طلبي؟',
  'Do you have it in grey?': 'عندكم منه رمادي؟',
  'Price?': 'بكم؟',
  'I sent the payment': 'حوّلت المبلغ',
  'When will it arrive?': 'متى يوصل؟',
  'Please call me': 'كلموني لو سمحتوا',
  'Is delivery free?': 'التوصيل ببلاش؟',
  'Can I return this?': 'أقدر أرجّعه؟',
  'Any discount?': 'فيه خصم؟',
  'Is this available?': 'متوفر؟',
  'Is this still available?': 'للحين متوفر؟',
  'Wrong item received': 'وصلني غرض غلط',
  'Wrong size delivered': 'وصلني مقاس غلط',
  'Wrong size': 'مقاس غلط',
  'Invoice copy please': 'أبي نسخة من الفاتورة',
  'Delivery time?': 'متى التوصيل؟',
  'Refund request #4790': 'طلب استرجاع #4790',
  'Can I change the color?': 'أقدر أغيّر اللون؟',
  'Thank you! Received.': 'مشكورين، وصلني!',
  'Is the rug washable?': 'السجادة تنغسل؟',
  'Hi! Where is my order #4822?': 'هلا، وين طلبي #4822؟',
  '“Can you hold the sofa until Thursday?”': '«ممكن تحجزون لي الكنبة لين الخميس؟»',

  /* people */
  'Noura A.': 'نورة أ.', 'Fahad K.': 'فهد ك.', 'Sara M.': 'سارة م.', 'Dana S.': 'دانة س.', 'Yousef M.': 'يوسف م.',
  'Mariam H.': 'مريم ح.', 'Ali R.': 'علي ر.', 'Huda B.': 'هدى ب.', 'Omar T.': 'عمر ت.', 'Reem S.': 'ريم س.', 'Khaled N.': 'خالد ن.',
  'Noura Ahmad': 'نورة أحمد', 'Ali Rashed': 'علي راشد',
  'Noura': 'نورة', 'Fahad': 'فهد', 'Sara': 'سارة', 'Dana': 'دانة', 'Ali': 'علي', 'Yousef': 'يوسف', 'Mariam': 'مريم',
  'Huda': 'هدى', 'Omar': 'عمر', 'Reem': 'ريم', 'Khaled': 'خالد', 'Lulwa': 'لولوة', 'Nasser': 'ناصر',
  'NA': 'ن', 'FK': 'ف', 'SM': 'س', 'DS': 'د', 'YM': 'ي', 'MH': 'م', 'AR': 'ع', 'HB': 'هـ', 'A': 'أ',

  /* products */
  'Linen Sofa': 'كنبة كتان', 'Velvet Ottoman': 'بوف مخمل', 'Lounge Chair': 'كرسي استرخاء', 'Oval Rug': 'سجادة بيضاوية',
  'Charge KWD 438.000': 'تحصيل 438.000 د.ك',
  'Floor Pouf': 'بوف أرضي', 'Coffee Table': 'طاولة قهوة', 'Linen Sofa × 1': 'كنبة كتان × 1', 'Floor Pouf × 2': 'بوف أرضي × 2',

  /* other tools (chaos) */
  'Shared · 4 editors': 'مشترك · 4 محررين',
  'Order': 'الطلب', 'Customer': 'العميل', 'Channel': 'القناة', 'Total': 'المجموع', 'Status': 'الحالة',
  'Instagram': 'إنستغرام', 'WhatsApp': 'واتساب', 'Website': 'الموقع', 'POS': 'نقطة البيع',
  'Pending': 'معلّق', 'Paid?': 'مدفوع؟', 'Failed': 'فشل', 'Unpaid': 'غير مدفوع', 'Unfulfilled': 'لم يُنفّذ', 'Cancelled': 'ملغي',
  'POS · Terminal 2': 'نقطة البيع · جهاز 2', 'POS · Terminal 1': 'نقطة البيع · جهاز 1', 'POS · Returns': 'نقطة البيع · المرتجعات',
  'Shift open · 6h 12m': 'الوردية مفتوحة · 6س 12د', 'Shift open': 'الوردية مفتوحة', 'Offline': 'غير متصل', '4 pending': '4 معلّقة',
  'Card': 'بطاقة', 'Cash': 'كاش', 'Refund': 'استرجاع', 'Void': 'إلغاء',
  'Invoice': 'فاتورة', 'INV-2291 · Due 14 days ago': 'INV-2291 · مستحقة منذ 14 يوماً', 'OVERDUE': 'متأخرة',
  'Delivery': 'التوصيل', 'Assembly': 'التركيب', 'Total due': 'المبلغ المستحق', 'Reminder not sent': 'لم يُرسل تذكير',
  '14 days overdue': 'متأخرة 14 يوماً',
  'Ads Manager': 'مدير الإعلانات', 'Account · Store KW': 'الحساب · المتجر', 'Store KW': 'المتجر',
  'Spend': 'الإنفاق', 'Results': 'النتائج', 'Cost/result': 'تكلفة النتيجة', 'CPA': 'تكلفة العميل',
  'Campaigns': 'الحملات', '3 running': '3 قيد التشغيل',
  'Support inbox': 'صندوق الدعم',
  'Sales report': 'تقرير المبيعات', 'Export · weekly': 'تصدير · أسبوعي', 'Weekly export': 'تصدير أسبوعي', 'Not synced': 'غير متزامن',
  'KWD 41,2··': '41,2·· د.ك',
  'BI export · weekly': 'تصدير BI · أسبوعي', 'Revenue (estimated)': 'الإيرادات (تقديرية)', 'Last synced 3 days ago': 'آخر مزامنة قبل 3 أيام',
  'Warehouse B': 'المستودع ب', 'SKU': 'الرمز', 'Item': 'الصنف', 'Count': 'الجرد', 'System': 'النظام',
  'Orders': 'الطلبات', 'Store admin · updated 2h ago': 'إدارة المتجر · آخر تحديث قبل ساعتين', 'Store admin': 'إدارة المتجر', '23 pending': '23 معلّق',
  'Contacts': 'جهات الاتصال', 'CRM · 2,384 records': 'CRM · 2,384 سجلاً', '2,384 records': '2,384 سجلاً',
  'Duplicate': 'مكرر', 'Dup.': 'مكرر', 'No phone': 'بلا رقم', 'Incomplete': 'ناقص', 'Unsubscribed': 'ألغى الاشتراك', 'No email': 'بلا بريد',
  'Accounting': 'المحاسبة', 'Date': 'التاريخ', 'Account': 'الحساب', 'Debit': 'مدين', 'Credit': 'دائن', 'Balance': 'الرصيد',
  'Sales': 'المبيعات', 'Inventory': 'المخزون', 'Rent': 'الإيجار', 'Refunds': 'المرتجعات', 'Shipping': 'الشحن', 'Ads': 'الإعلانات',
  'Unreconciled': 'غير مطابق', 'Salaries': 'الرواتب', 'POS diff.': 'فرق الصندوق', '???': '؟؟؟',
  'WHATSAPP': 'واتساب', 'CUSTOMERS': 'العملاء', 'ACCOUNTING': 'المحاسبة', 'SALES': 'المبيعات', 'ORDERS': 'الطلبات',
  'Orders → Accounting': 'الطلبات ← المحاسبة', 'WhatsApp → Orders': 'واتساب ← الطلبات',
  'Data mismatch': 'بيانات غير متطابقة', 'Sales vs. Customers': 'المبيعات مقابل العملاء', 'Not connected': 'غير مرتبط',

  /* notifications */
  'New order #4821': 'طلب جديد #4821', 'New order #4822': 'طلب جديد #4822', 'New order #4823': 'طلب جديد #4823',
  'New order #4824': 'طلب جديد #4824', 'New order #4825': 'طلب جديد #4825',
  '3 new messages': '3 رسائل جديدة', '5 new messages': '5 رسائل جديدة', 'Payment failed': 'فشل الدفع',
  'Card declined · #4817': 'رُفضت البطاقة · #4817', 'Low stock': 'مخزون منخفض', 'Velvet Ottoman · 2 left': 'بوف مخمل · باقي 2',
  'New DM': 'رسالة جديدة', 'Refund requested': 'طلب استرجاع', 'Order #4790': 'طلب #4790', 'Order #4815': 'طلب #4815',
  'Missed call': 'مكالمة فائتة', 'Customer · 2 min ago': 'عميل · قبل دقيقتين', 'Invoice overdue': 'فاتورة متأخرة',
  'INV-2291 · 14 days': 'INV-2291 · 14 يوماً', 'Sync failed': 'فشلت المزامنة', 'Inventory not updated': 'المخزون لم يُحدَّث',
  'Driver not assigned': 'لم يُعيَّن سائق', 'Out of stock': 'نفد المخزون', 'Chargeback': 'استرداد بنكي', '12 unread': '12 غير مقروءة',
  'Instagram DMs': 'رسائل إنستغرام', 'Order cancelled': 'طلب ملغي', 'Price mismatch': 'اختلاف في السعر', 'POS vs. website': 'المحل مقابل الموقع',
  'New review · 2/5': 'تقييم جديد · 2/5', 'Late delivery': 'تأخر التوصيل', 'WhatsApp · Noura': 'واتساب · نورة',
  'Stock count error': 'خطأ في الجرد', 'Instagram · unpaid': 'إنستغرام · غير مدفوع', 'Duplicate contact': 'عميل مكرر',
  'Noura A. · 3 records': 'نورة أ. · 3 سجلات', 'INV-2291 · KWD 409.000': 'INV-2291 · 409.000 د.ك', 'Sales data · 3 days': 'بيانات المبيعات · 3 أيام',

  /* velorci interface */
  'Cart': 'السلة', 'Good evening': 'مساء الخير', 'Overview': 'نظرة عامة', 'Today': 'اليوم', 'Revenue': 'الإيرادات', 'KWD': 'د.ك',
  'Customers': 'العملاء', '+64 new': '+64 جديد', 'Last 7 days': 'آخر 7 أيام', 'Live': 'مباشر',
  '3 visits this week': '3 زيارات هذا الأسبوع', 'VIP · 23 orders': 'VIP · 23 طلباً', '3 sites': '3 مواقع', '6 left': 'باقي 6',
  'WhatsApp · 2 days ago': 'واتساب · قبل يومين',
  'Every channel, one queue': 'كل القنوات في لوحة واحدة', 'Orders today': 'طلبات اليوم',
  'New': 'جديد', 'Preparing': 'قيد التجهيز', 'On the way': 'في الطريق', 'Delivered': 'تم التسليم',
  'Sell in-store, synced live': 'مبيعات المحل متزامنة فوراً',
  'CRM': 'العملاء', 'Know every customer': 'اعرف كل عميل', 'Repeat buyer': 'عميل متكرر', 'Lifetime value': 'القيمة الإجمالية',
  'Ordered Linen Sofa': 'طلب كنبة كتان', '2 days ago': 'قبل يومين', 'Asked about delivery on WhatsApp': 'سأل عن التوصيل عبر واتساب',
  '3 days ago': 'قبل 3 أيام', 'Opened Autumn Collection': 'فتح حملة مجموعة الخريف', '5 days ago': 'قبل 5 أيام',
  'Stock that updates itself': 'مخزون يحدّث نفسه', 'Items in stock': 'قطعة في المخزون', 'Warehouses': 'مستودعات', '6 · Low': '6 · منخفض',
  'Books that close themselves': 'حسابات تُقفل نفسها', 'Net profit · September': 'صافي الربح · سبتمبر', '↑ 22% vs. August': '↑ 22% عن أغسطس',
  'Expenses': 'المصاريف', 'Apr': 'أبريل', 'May': 'مايو', 'Jun': 'يونيو', 'Jul': 'يوليو', 'Aug': 'أغسطس', 'Sep': 'سبتمبر',
  'Conversations that convert': 'محادثات تتحول إلى مبيعات', '2m': '2د', '8m': '8د', '15m': '15د',
  'Out for delivery, arriving by 6 PM.': 'طلبك مع المندوب، ويصلك قبل 6 مساءً.', 'Auto-reply sent': 'أُرسل الرد تلقائياً',
  'Marketing': 'التسويق', 'Campaigns with real ROI': 'حملات بعائد واضح', 'ROAS this month': 'العائد على الإعلان', 'Attributed revenue': 'إيرادات من الحملات',
  'Autumn Collection': 'مجموعة الخريف', 'Win-back': 'استعادة العملاء', 'WhatsApp broadcast': 'بث واتساب', 'Search': 'البحث', 'Google': 'جوجل',
  'New arrivals': 'وصل حديثاً', 'Email': 'البريد',
  'Analytics': 'التحليلات', 'Every number, in real time': 'كل رقم، لحظة بلحظة', 'Revenue · this month': 'الإيرادات · هذا الشهر',
  'Conversion': 'التحويل', 'Avg. order': 'متوسط الطلب', 'Returning': 'عملاء عائدون',
  'Automation': 'الأتمتة', 'Workflows on autopilot': 'سير عمل يعمل وحده', 'When': 'عند', 'Then': 'ثم', 'After delivery': 'بعد التسليم',
  'New order received': 'استلام طلب جديد', 'Send WhatsApp confirmation': 'إرسال تأكيد عبر واتساب', 'Update inventory': 'تحديث المخزون',
  'Assign a driver': 'تعيين سائق', 'Ask for a review': 'طلب تقييم',
  'AI': 'ذكاء اصطناعي', 'Your built-in analyst': 'محلّلك الخاص', 'How did we do this week?': 'كيف كان أداؤنا هذا الأسبوع؟',
  'Create restock order': 'إنشاء طلب توريد', 'Notify top customers': 'تنبيه أفضل العملاء', 'Weekly report': 'التقرير الأسبوعي',
  'AI INSIGHT': 'تنبيه ذكي', 'Sales opportunity detected': 'رُصدت فرصة بيع', 'Customer ready to buy': 'عميل جاهز للشراء',
  'Low stock detected': 'المخزون منخفض', 'Follow-up recommended': 'يُنصح بالمتابعة',
};
